### ISSUE TITLE
Print string values with HTML line breaks

### ISSUE THREAD

**Issue by dustinblack** [arcalot/arcaflow-docsgen#26]
## Please describe what you would like to see in this project

Long string values (particularly in schema item descriptions) are rendered a one long non-breaking line. We should set a maximum length for a string value and apply the HTML/CSS necessary to render the text with line breaks for readability.

**Comment by jaredoconnell** [comment]
Do you have a link to or a screenshot of one of the problematic ones? Is it extending beyond the bounds of the page, or is it just that the page is so wide that it isn't the most readable?

**Comment by webbnh** [comment]
Go to [this page](https://github.com/arcalot/arcaflow-plugin-pcp/blob/5c485a4f284db3d77d49af901b46619c7e6f2130/README.md), expand the `pmrep_conf` property, and look at the description.
